export const database = [
	{
		id: 1,
		title: "Jeff Banks Classic Beige Suit",
		imageFront: "./img/suit-1/suit-front.jpg",
		imageBack: "./img/suit-1/suit-back.jpg",
		price: 244,
		category: "suit",
	},
	{
		id: 2,
		title: "Racing Green Tailored Navy Suit",
		imageFront: "./img/suit-2/suit-front.jpg",
		imageBack: "./img/suit-2/suit-back.jpg",
		price: 340,
		category: "suit",
	},
	{
		id: 3,
		title: "Antique Rogue Light Blue Suit",
		imageFront: "./img/suit-3/suit-front.jpg",
		imageBack: "./img/suit-3/suit-back.jpg",
		price: 144,
		category: "suit",
	},
	{
		id: 4,
		title: "Ben Sherman Slim Grey Suit",
		imageFront: "./img/suit-4/suit-front.jpg",
		imageBack: "./img/suit-4/suit-back.jpg",
		price: 544,
		category: "suit",
	},
	{
		id: 5,
		title: "Racing Green Black Twill Suit",
		imageFront: "./img/suit-5/suit-front.jpg",
		imageBack: "./img/suit-5/suit-back.jpg",
		price: 644,
		category: "suit",
	},
	{
		id: 6,
		title: "Limehaus Slim Pink Texture Suit",
		imageFront: "./img/suit-6/suit-front.jpg",
		imageBack: "./img/suit-6/suit-back.jpg",
		price: 150,
		category: "suit",
	},
	{
		id: 7,
		title: "Jack & Jones White Faux Trainer",
		imageFront: "./img/shoes/shoe-1.jpg",
		imageBack: "./img/shoes/shoe-1-back.jpg",
		price: 134,
		category: "shoe",
	},
	{
		id: 8,
		title: "Racing Green Black Brogues",
		imageFront: "./img/shoes/shoe-2.jpg",
		imageBack: "./img/shoes/shoe-2-back.jpg",
		price: 44,
		category: "shoe",
	},
	{
		id: 9,
		title: "Racing Green Tan Brogues",
		imageFront: "./img/shoes/shoe-3.jpg",
		imageBack: "./img/shoes/shoe-3-back.jpg",
		price: 46,
		category: "shoe",
	},
	{
		id: 10,
		title: "Black Slip on Formal Shoes",
		imageFront: "./img/shoes/shoe-4.jpg",
		imageBack: "./img/shoes/shoe-4-back.jpg",
		price: 32,
		category: "shoe",
	},
	{
		id: 11,
		title: "Ben Sherman Fulford Loafers",
		imageFront: "./img/shoes/shoe-5.jpg",
		imageBack: "./img/shoes/shoe-5-back.jpg",
		price: 20,
		category: "shoe",
	},
	{
		id: 12,
		title: "Tan Lace up Brogues",
		imageFront: "./img/shoes/shoe-6.jpg",
		imageBack: "./img/shoes/shoe-6-back.jpg",
		price: 24,
		category: "shoe",
	},
	{
		id: 13,
		title: "Jeff Banks Navy Melton Cap",
		imageFront: "./img/acessorios/hat-1.jpg",
		imageBack: "./img/acessorios/hat-1.jpg",
		price: 10,
		category: "accessory",
	},
	{
		id: 14,
		title: "Jeff Banks Herringbone Baker",
		imageFront: "./img/acessorios/hat-2.jpg",
		imageBack: "./img/acessorios/hat-2.jpg",
		price: 14,
		category: "accessory",
	},
	{
		id: 15,
		title: "Gibson London Brown Hat",
		imageFront: "./img/acessorios/hat-3.jpg",
		imageBack: "./img/acessorios/hat-3.jpg",
		price: 24,
		category: "accessory",
	},
	{
		id: 16,
		title: "Gray Herringbone Baker",
		imageFront: "./img/acessorios/hat-4.jpg",
		imageBack: "./img/acessorios/hat-4.jpg",
		price: 20,
		category: "accessory",
	},
	{
		id: 17,
		title: "Black Bifold Colour Panel",
		imageFront: "./img/acessorios/wallet-1.jpg",
		imageBack: "./img/acessorios/wallet-1.jpg",
		price: 10,
		category: "accessory",
	},
	{
		id: 18,
		title: "Tan Crocodile Card Holder",
		imageFront: "./img/acessorios/wallet-2.jpg",
		imageBack: "./img/acessorios/wallet-2.jpg",
		price: 44,
		category: "accessory",
	},
	{
		id: 19,
		title: "Black Bifold Front Card Slot",
		imageFront: "./img/acessorios/wallet-3.jpg",
		imageBack: "./img/acessorios/wallet-3.jpg",
		price: 14,
		category: "accessory",
	},
	{
		id: 20,
		title: "Jeff Banks Bifold Wallet",
		imageFront: "./img/acessorios/wallet-4.jpg",
		imageBack: "./img/acessorios/wallet-4.jpg",
		price: 30,
		category: "accessory",
	},
];
